package com.myspace.testing;

import com.myspace.testing.RuleBaseHelperJava;

declare MedicalChart
    name : String
    specialityType : String
    mobileNo : String
    cptCode: String
end

rule 'cpt 1'
	when
		medChart: MedicalChart( mobileNo != null)
	then
		medChart.setCptCode("1111");
end

rule 'cpt 2'
	when
		medChart: MedicalChart(specialityType == 1)
	then
		medChart.setCptCode("1112");
end

rule 'cpt 3'
	when
		medChart: MedicalChart(RuleBaseHelperJava.stringCompareJava(specialityType,"hello"))
	then
		medChart.setCptCode("Hey Hello");
end

rule 'cpt 4'
	when
		medChart: MedicalChart(RuleBaseHelperJava.stringCompareJava(specialityType,"world"))
	then
		medChart.setCptCode("Hey World");
end
